AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create S3 Bucket for Website Access

Parameters:
  BucketName:
    Type: String
    Default: 'your-bucket-name'

Resources:
  SrcImageS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Join
        - ''
        - - !Ref BucketName
          - '-src'

  ResizedImageS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Join
        - ''
        - - !Ref BucketName
          - '-resized'
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"

  ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResizedImageS3Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${ResizedImageS3Bucket}/*"
            Principal: "*"

Outputs:
  SrcBucketRef:
    Description: "S3 Bucket for Src Image Ref"
    Value: !Ref SrcImageS3Bucket
  ResizedImageBucketRef:
    Description: "S3 Bucket for Resized Image Ref"
    Value: !Ref ResizedImageS3Bucket
  ResizedImageBucketUrl:
    Description: "S3 Bucket for Resized Image Url"
    Value: !GetAtt ResizedImageS3Bucket.WebsiteURL
